# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.qr_info = QtWidgets.QLabel(self.centralwidget)
        self.qr_info.setGeometry(QtCore.QRect(1340, 500, 480, 480))
        self.qr_info.setMinimumSize(QtCore.QSize(0, 0))
        self.qr_info.setText("")
        self.qr_info.setObjectName("qr_info")
        self.car_frame = QtWidgets.QLabel(self.centralwidget)
        self.car_frame.setGeometry(QtCore.QRect(1260, 20, 640, 480))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.car_frame.setFont(font)
        self.car_frame.setText("")
        self.car_frame.setObjectName("car_frame")
        self.sale_info = QtWidgets.QLabel(self.centralwidget)
        self.sale_info.setGeometry(QtCore.QRect(10, 20, 1230, 480))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sale_info.setFont(font)
        self.sale_info.setText("")
        self.sale_info.setAlignment(QtCore.Qt.AlignCenter)
        self.sale_info.setObjectName("sale_info")
        self.shop_info = QtWidgets.QLabel(self.centralwidget)
        self.shop_info.setGeometry(QtCore.QRect(10, 530, 1230, 260))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shop_info.setFont(font)
        self.shop_info.setText("")
        self.shop_info.setAlignment(QtCore.Qt.AlignCenter)
        self.shop_info.setObjectName("shop_info")
        self.user_info = QtWidgets.QLabel(self.centralwidget)
        self.user_info.setGeometry(QtCore.QRect(10, 800, 1230, 260))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_info.setFont(font)
        self.user_info.setText("")
        self.user_info.setAlignment(QtCore.Qt.AlignCenter)
        self.user_info.setObjectName("user_info")
        self.btn_sale_info = QtWidgets.QToolButton(self.centralwidget)
        self.btn_sale_info.setGeometry(QtCore.QRect(1320, 1000, 160, 22))
        self.btn_sale_info.setObjectName("btn_sale_info")
        self.btn_car_frame = QtWidgets.QToolButton(self.centralwidget)
        self.btn_car_frame.setGeometry(QtCore.QRect(1530, 1000, 160, 22))
        self.btn_car_frame.setObjectName("btn_car_frame")
        self.btn_user_info = QtWidgets.QToolButton(self.centralwidget)
        self.btn_user_info.setGeometry(QtCore.QRect(1740, 1000, 160, 22))
        self.btn_user_info.setObjectName("btn_user_info")
        self.btn_qr_info = QtWidgets.QToolButton(self.centralwidget)
        self.btn_qr_info.setGeometry(QtCore.QRect(1320, 1040, 160, 22))
        self.btn_qr_info.setObjectName("btn_qr_info")
        self.btn_shop_info = QtWidgets.QToolButton(self.centralwidget)
        self.btn_shop_info.setGeometry(QtCore.QRect(1530, 1040, 160, 22))
        self.btn_shop_info.setObjectName("btn_shop_info")
        self.btn_clear = QtWidgets.QToolButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(1740, 1040, 160, 22))
        self.btn_clear.setObjectName("btn_clear")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TV"))
        self.btn_sale_info.setText(_translate("MainWindow", "SALE_INFO"))
        self.btn_car_frame.setText(_translate("MainWindow", "CAR_FRAME"))
        self.btn_user_info.setText(_translate("MainWindow", "USER_INFO"))
        self.btn_qr_info.setText(_translate("MainWindow", "QR_INFO"))
        self.btn_shop_info.setText(_translate("MainWindow", "SHOP_INFO"))
        self.btn_clear.setText(_translate("MainWindow", "CLEAR"))
