# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1043)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img_info = QtWidgets.QLabel(self.centralwidget)
        self.img_info.setGeometry(QtCore.QRect(10, 9, 1900, 971))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.img_info.setFont(font)
        self.img_info.setText("")
        self.img_info.setAlignment(QtCore.Qt.AlignCenter)
        self.img_info.setObjectName("img_info")
        self.btn_welcome = QtWidgets.QToolButton(self.centralwidget)
        self.btn_welcome.setGeometry(QtCore.QRect(20, 1010, 160, 22))
        self.btn_welcome.setObjectName("btn_welcome")
        self.btn_car_frame = QtWidgets.QToolButton(self.centralwidget)
        self.btn_car_frame.setGeometry(QtCore.QRect(420, 1010, 160, 22))
        self.btn_car_frame.setObjectName("btn_car_frame")
        self.btn_car_in = QtWidgets.QToolButton(self.centralwidget)
        self.btn_car_in.setGeometry(QtCore.QRect(1040, 1010, 160, 22))
        self.btn_car_in.setObjectName("btn_car_in")
        self.btn_qr_info = QtWidgets.QToolButton(self.centralwidget)
        self.btn_qr_info.setGeometry(QtCore.QRect(620, 1010, 160, 22))
        self.btn_qr_info.setObjectName("btn_qr_info")
        self.btn_plate = QtWidgets.QToolButton(self.centralwidget)
        self.btn_plate.setGeometry(QtCore.QRect(220, 1010, 160, 22))
        self.btn_plate.setObjectName("btn_plate")
        self.btn_clear = QtWidgets.QToolButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(1240, 1010, 160, 22))
        self.btn_clear.setObjectName("btn_clear")
        self.btn_pay_succeed = QtWidgets.QToolButton(self.centralwidget)
        self.btn_pay_succeed.setGeometry(QtCore.QRect(820, 1010, 160, 22))
        self.btn_pay_succeed.setObjectName("btn_pay_succeed")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TV"))
        self.btn_welcome.setText(_translate("MainWindow", "WELCOME"))
        self.btn_car_frame.setText(_translate("MainWindow", "CAR_FRAME"))
        self.btn_car_in.setText(_translate("MainWindow", "CAR_IN"))
        self.btn_qr_info.setText(_translate("MainWindow", "QR_INFO"))
        self.btn_plate.setText(_translate("MainWindow", "PLATE"))
        self.btn_clear.setText(_translate("MainWindow", "CLEAR"))
        self.btn_pay_succeed.setText(_translate("MainWindow", "PAY_SUCCEED"))
